#spring:
#  datasource:
#    url: jdbc:mysql://ec2-3-25-88-85.ap-southeast-2.compute.amazonaws.com:3306/social_media
#    username: monit
#    password: Mg@intellia123
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
##    database-platform: org.hibernate.dialect.MySQL8Dialect
#
#
#  flyway:
#    url: jdbc:mysql://ec2-3-25-88-85.ap-southeast-2.compute.amazonaws.com:3306/social_media
#    schemas: social_media
#    user: "monit"
#    password: "Mg@intellia123"
#    baselineOnMigrate: true
#    enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/social_media
    username: root
    password: Adnan@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
  #    database-platform: org.hibernate.dialect.MySQL8Dialect


  flyway:
    url: jdbc:mysql://localhost:3306/social_media
    schemas: social_media
    user: "root"
    password: "Adnan@123"
    baselineOnMigrate: true
    enabled: true
