--
--CREATE TABLE hashtag_mst (
--    id INT AUTO_INCREMENT PRIMARY KEY,
--    name VARCHAR(255) UNIQUE NOT NULL,
--    created_at TIMESTAMP NOT NULL
--);
--
--INSERT INTO hashtag_mst (name, created_at)
--VALUES
--    ('#EntertainmentBuzz', NOW()),
--    ('#MovieNightFun', NOW()),
--    ('#CelebSpotlight', NOW()),
--    ('#HollywoodScene', NOW()),
--    ('#PopCultureHub', NOW()),
--
--    ('#HealthyLiving', NOW()),
--    ('#TravelAdventures', NOW()),
--    ('#FashionInspo', NOW()),
--    ('#FoodieAdventures', NOW()),
--    ('#LifeGoals', NOW()),
--
--    ('#MotivationMonday', NOW()),
--    ('#DreamBig', NOW()),
--    ('#InspireOthers', NOW()),
--    ('#PositiveVibes', NOW()),
--    ('#GoalSetting', NOW()),
--
--    ('#FoodieDelights', NOW()),
--    ('#CookingAdventures', NOW()),
--    ('#TastyRecipes', NOW()),
--    ('#FoodieHeaven', NOW()),
--    ('#GourmetCooking', NOW()),
--
--    ('#Wanderlust', NOW()),
--    ('#AdventureAwaits', NOW()),
--    ('#ExploreTheWorld', NOW()),
--    ('#TravelGoals', NOW()),
--    ('#Backpacking', NOW()),
--
--    ('#Fashionista', NOW()),
--    ('#StyleInspiration', NOW()),
--    ('#FashionTrends', NOW()),
--    ('#StreetStyle', NOW()),
--    ('#DesignerFashion', NOW()),
--
--    ('#TechTrends', NOW()),
--    ('#Innovation', NOW()),
--    ('#Gadgets', NOW()),
--    ('#TechGeeks', NOW()),
--    ('#DigitalWorld', NOW()),
--
--    ('#LearnEveryday', NOW()),
--    ('#KnowledgeIsPower', NOW()),
--    ('#OnlineLearning', NOW()),
--    ('#EducationalTech', NOW()),
--    ('#StudyMotivation', NOW()),
--
--    ('#PetLovers', NOW()),
--    ('#AdoptDontShop', NOW()),
--    ('#AnimalRescue', NOW()),
--    ('#CutePets', NOW()),
--    ('#FurBabies', NOW()),
--
--    ('#HealthyLiving', NOW()),
--    ('#WellnessJourney', NOW()),
--    ('#MentalHealthMatters', NOW()),
--    ('#FitnessGoals', NOW()),
--    ('#SelfCare', NOW()),
--
--    ('#HomeSweetHome', NOW()),
--    ('#InteriorDesign', NOW()),
--    ('#HomeDecor', NOW()),
--    ('#DIYProjects', NOW()),
--    ('#CozySpaces', NOW()),
--
--    ('#LaughOutLoud', NOW()),
--    ('#ComedyNights', NOW()),
--    ('#StandUpComedy', NOW()),
--    ('#FunnyMemes', NOW()),
--    ('#Hilarious', NOW()),
--
--    ('#MusicIsLife', NOW()),
--    ('#SongOfTheDay', NOW()),
--    ('#MusicLovers', NOW()),
--    ('#ConcertVibes', NOW()),
--    ('#MusicalTalent', NOW()),
--
--    ('#BeautyObsession', NOW()),
--    ('#MakeupAddict', NOW()),
--    ('#GlowUp', NOW()),
--    ('#SkincareRoutine', NOW()),
--    ('#BeautyTips', NOW()),
--
--    ('#GamerLife', NOW()),
--    ('#GamingCommunity', NOW()),
--    ('#GameOn', NOW()),
--    ('#Esports', NOW()),
--    ('#ConsoleGaming', NOW()),
--
--    ('#CreativeInspiration', NOW()),
--    ('#ArtisticExpression', NOW()),
--    ('#DIYArt', NOW()),
--    ('#ArtisticTalent', NOW()),
--    ('#PaintingPassion', NOW()),
--
--    ('#FitnessJourney', NOW()),
--    ('#SportsMania', NOW()),
--    ('#ActiveLifestyle', NOW()),
--    ('#WorkoutMotivation', NOW()),
--    ('#AthleteLife', NOW()),
--
--    ('#FamilyTime', NOW()),
--    ('#ParentingTips', NOW()),
--    ('#Parenthood', NOW()),
--    ('#FamilyAdventures', NOW()),
--    ('#KidsFun', NOW()),
--
--    ('#NatureLovers', NOW()),
--    ('#EcoFriendly', NOW()),
--    ('#WildlifeAdventures', NOW()),
--    ('#GreenLiving', NOW()),
--    ('#OutdoorExploration', NOW()),
--
--    ('#ScienceGeeks', NOW()),
--    ('#TechInnovation', NOW()),
--    ('#STEMEducation', NOW()),
--    ('#ScientificDiscovery', NOW()),
--    ('#TechTrends', NOW());
--
